require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/placa_carros", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PlacaCarro. As you add validations to PlacaCarro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PlacaCarro.create! valid_attributes
      get placa_carros_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      placa_carro = PlacaCarro.create! valid_attributes
      get placa_carro_url(placa_carro)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_placa_carro_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      placa_carro = PlacaCarro.create! valid_attributes
      get edit_placa_carro_url(placa_carro)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PlacaCarro" do
        expect {
          post placa_carros_url, params: { placa_carro: valid_attributes }
        }.to change(PlacaCarro, :count).by(1)
      end

      it "redirects to the created placa_carro" do
        post placa_carros_url, params: { placa_carro: valid_attributes }
        expect(response).to redirect_to(placa_carro_url(PlacaCarro.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PlacaCarro" do
        expect {
          post placa_carros_url, params: { placa_carro: invalid_attributes }
        }.to change(PlacaCarro, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post placa_carros_url, params: { placa_carro: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested placa_carro" do
        placa_carro = PlacaCarro.create! valid_attributes
        patch placa_carro_url(placa_carro), params: { placa_carro: new_attributes }
        placa_carro.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the placa_carro" do
        placa_carro = PlacaCarro.create! valid_attributes
        patch placa_carro_url(placa_carro), params: { placa_carro: new_attributes }
        placa_carro.reload
        expect(response).to redirect_to(placa_carro_url(placa_carro))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        placa_carro = PlacaCarro.create! valid_attributes
        patch placa_carro_url(placa_carro), params: { placa_carro: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested placa_carro" do
      placa_carro = PlacaCarro.create! valid_attributes
      expect {
        delete placa_carro_url(placa_carro)
      }.to change(PlacaCarro, :count).by(-1)
    end

    it "redirects to the placa_carros list" do
      placa_carro = PlacaCarro.create! valid_attributes
      delete placa_carro_url(placa_carro)
      expect(response).to redirect_to(placa_carros_url)
    end
  end
end
